---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# blantyreSepsis

<!-- badges: start -->
<!-- badges: end -->

The BlantyreSepsis R package contains data and code to replicate the analysis of the manuscript:
  
<br />

*Aetiology and determinants of outcome in sepsis in an urban African centre: an observational cohort study*

<br />

Joseph M Lewis^1,2,3^, , Madlatso Mphasa^1^, Lucy Keyala^1^, Rachel Banda^1^, Emma Smith^1^,^2^,  Jackie Duggan^4^, Tim Brooks^4^, Matthew Catton^4^, Jane Mallewa^5^, Grace Katha^5^, Brian Faragher^2^, Melita Gordon^1,3^, Jamie Rylance^1,2^, Nicholas A Feasey^1,2^

1. Malawi Liverpool Wellcome Clinical Research Programme, Blantyre, Malawi
2. Department of Clinical Sciences, Liverpool School of Tropical Medicine, Liverpool, UK
3. Department of Clinical Infection, Microbiology and Immunology, University of Liverpool, Liverpool, UK
4. Rare and Imported Pathogens Laboratory, Public Health England, UK
5. Malawi College of Medicine, University of Malawi

## Installing and accessing data

Install the package from GitHub:

``` r
install.packages("devtools")
devtools::install_github("https://github.com/joelewis101/blantyreSepsis")
```

Or check out the source code at [GitHub](https://github.com/joelewis101/blantyreSepsis) 

Six datasets are included in the package; for details and variable definitions access the associated help file (e.g via `?BTparticipants`)

* `BTparticipants` - Baseline characteristics and investigation results for included participants
* `BTtreatments` - Antimicrobial therapy and intravenous fluid therapy received by included participants
* `BTaetiology` - Results of malaria testing, aerobic blood culture, cerebrospinalfluid culture, tuberculosis diagnostic tests
* `BTsera` - Results of serologic tests for arboviruses, Rickettsioses, Leptospirosis
* `BTarraycard` - Results of multiplex PCR test for high consequence pathogens
* `BTbc` - Results of aerobic blood culture

This analysis is available as a package vignette; this can be built when downloading the package by typing:

``` r
devtools::install_github("https://github.com/joelewis101/blantyreSepsis", build_vignettes = TRUE )
```

The vignette will be then be available by typing `vignette("analysis")` and the code is accessed by typing `edit(vigentte("analysis"))`. Be warned: building the vignette takes some time as it will run through the full missing data imputation and model fitting!

Alternatively the source code for the vignette is `analysis.Rmd` or the  [pkgdown](https://joelewis101.github.io/blantyreSepsis/) site for this package has a rendered version, as well as variable definitions for the datasets.


